### ISSUE TITLE
Support parallel verification of message values with given HMAC key

### ISSUE THREAD

**Issue by mycognosist** [sunrise-choir/ssb-verify-signatures#3]
I'm working on supporting message signature verification with a user-defined HMAC key. This is necessary if we want to be able to verify messages which were created with an alternate HMAC key (ie. a parallel Scuttleverse which does not use `NetworkKey::SSB_MAIN_NET`).

Verifying the signature for a single message value with a given HMAC is simple, thanks to the excellent work on [ssb-crypto](https://docs.rs/ssb-crypto/0.2.2/ssb_crypto/). I have this working on a branch, with code as follows ([source](https://github.com/mycognosist/ssb-verify-signatures/blob/hmac_support/src/lib.rs#L195)):

```rust
pub fn verify_message_value_with_hmac<T: AsRef<[u8]>>(msg: T, hmac: &[u8]) -> Result<()> {
    let (key, sig, bytes) = get_pubkey_sig_bytes_from_ssb_message_value(msg.as_ref())?;
    let hmac_key = NetworkKey::from_slice(hmac).context(InvalidHmac)?;
    let tag = hmac_key.authenticate(&bytes);
    let tag_bytes = tag.as_bytes();
    key.verify(tag_bytes, &sig)
        .map_err(|_| snafu::NoneError)
        .context(InvalidSignature)
}
```

And a passing test:

```rust
#[test]
fn verify_message_value_with_hmac_works() {
    let msg = VALID_MESSAGE_VALUE_UNIQUE_HMAC.as_bytes();
    let hmac = base64::decode("CbwuwYXmZgN7ZSuycCXoKGOTU1dGwBex+paeA2kr37U=").unwrap();
    let result = verify_message_value_with_hmac(&msg, &hmac);
    assert!(result.is_ok());
}
```

That's the easy part. What I'm struggling with is the parallel implementation of this verification.

As I see it, we need the following two functions: `par_verify_message_values_with_hmac` and `par_verify_with_hmac`. The second of these functions should closely match the code in [`par_verify`](https://github.com/mycognosist/ssb-verify-signatures/blob/hmac_support/src/lib.rs#L312), with the difference being that it needs to iterate over the message bytes in `keys_sigs_bytes`, compute the HMAC tag for each message (with the given HMAC key) and collect the tags into an `ArrayVec` so it can be passed into `dalek_verify_batch` along with the `sigs` and `keys`.

I'm working on the aforementioned solution but am running into issues with borrowed values (from the `tag` generation).

Pinging @sbillig and @pietgeursen . Would love to hear any thoughts you have!

**Comment by sbillig** [comment]
Hey @mycognosist, I'd be happy to take a look. Could you push your not-compiling code up to a branch somewhere?

**Comment by mycognosist** [comment]
Hey @sbillig, thanks so much for the response. You'll find my latest code [here](https://github.com/mycognosist/ssb-verify-signatures/tree/hmac_support).

**Comment by sbillig** [comment]
@mycognosist I think the best you can do here is something like this:

```rust
let bytes_arrays = keys_sigs_bytes
    .iter()
    // TODO: handle the unwrap
    .map(|(_, _, msg)| get_hmac_tag_bytes(&hmac_key, &msg).unwrap())
    .collect::<ArrayVec<[[u8; 32]; CHUNK_SIZE]>>();
let bytes_slices = bytes_arrays
    .iter()
    .map(|array| &array[..])
    .collect::<ArrayVec<[&[u8]; CHUNK_SIZE]>>();
dalek_verify_batch(bytes_slices.as_slice(), sigs.as_slice(), keys.as_slice())
    .map_err(|_| snafu::NoneError)
    .context(InvalidSignature)
```

Ie collect the hmac tag arrays in an array (they have to live *somewhere* if they're going to be referenced), then collect slices of them in another array. (I suspect that this will have approximately zero negative impact on performance, fwiw)

**Comment by mycognosist** [comment]
Perfect, thanks so much! The intermediate `bytes_arrays` assignment makes a lot of sense. I think I came close to reaching this solution but wasn't quite there. Really appreciate you taking the time to help out.

**Comment by sbillig** [comment]
Any time! I'm happy to see you're working on this.

**Comment by mycognosist** [comment]
Support introduced in https://github.com/sunrise-choir/ssb-verify-signatures/pull/4
